// Generated by gencpp from file sandwich_robot/object_pose.msg
// DO NOT EDIT!


#ifndef SANDWICH_ROBOT_MESSAGE_OBJECT_POSE_H
#define SANDWICH_ROBOT_MESSAGE_OBJECT_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sandwich_robot
{
template <class ContainerAllocator>
struct object_pose_
{
  typedef object_pose_<ContainerAllocator> Type;

  object_pose_()
    : header()
    , x_pose()
    , y_pose()
    , num_items(0.0)  {
    }
  object_pose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x_pose(_alloc)
    , y_pose(_alloc)
    , num_items(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _x_pose_type;
  _x_pose_type x_pose;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _y_pose_type;
  _y_pose_type y_pose;

   typedef float _num_items_type;
  _num_items_type num_items;





  typedef boost::shared_ptr< ::sandwich_robot::object_pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sandwich_robot::object_pose_<ContainerAllocator> const> ConstPtr;

}; // struct object_pose_

typedef ::sandwich_robot::object_pose_<std::allocator<void> > object_pose;

typedef boost::shared_ptr< ::sandwich_robot::object_pose > object_posePtr;
typedef boost::shared_ptr< ::sandwich_robot::object_pose const> object_poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sandwich_robot::object_pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sandwich_robot::object_pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sandwich_robot::object_pose_<ContainerAllocator1> & lhs, const ::sandwich_robot::object_pose_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x_pose == rhs.x_pose &&
    lhs.y_pose == rhs.y_pose &&
    lhs.num_items == rhs.num_items;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sandwich_robot::object_pose_<ContainerAllocator1> & lhs, const ::sandwich_robot::object_pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sandwich_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sandwich_robot::object_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sandwich_robot::object_pose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sandwich_robot::object_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sandwich_robot::object_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sandwich_robot::object_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sandwich_robot::object_pose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sandwich_robot::object_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca7e8735ece8702de0499ffa6d63bc95";
  }

  static const char* value(const ::sandwich_robot::object_pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca7e8735ece8702dULL;
  static const uint64_t static_value2 = 0xe0499ffa6d63bc95ULL;
};

template<class ContainerAllocator>
struct DataType< ::sandwich_robot::object_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sandwich_robot/object_pose";
  }

  static const char* value(const ::sandwich_robot::object_pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sandwich_robot::object_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32[] x_pose\n"
"float32[] y_pose\n"
"float32 num_items\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sandwich_robot::object_pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sandwich_robot::object_pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x_pose);
      stream.next(m.y_pose);
      stream.next(m.num_items);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct object_pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sandwich_robot::object_pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sandwich_robot::object_pose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x_pose[]" << std::endl;
    for (size_t i = 0; i < v.x_pose.size(); ++i)
    {
      s << indent << "  x_pose[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x_pose[i]);
    }
    s << indent << "y_pose[]" << std::endl;
    for (size_t i = 0; i < v.y_pose.size(); ++i)
    {
      s << indent << "  y_pose[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y_pose[i]);
    }
    s << indent << "num_items: ";
    Printer<float>::stream(s, indent + "  ", v.num_items);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SANDWICH_ROBOT_MESSAGE_OBJECT_POSE_H
